// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleAccount.Preferences.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SimpleAccount.Preferences.Data.Migrations
{
    [DbContext(typeof(PreferencesDbContext))]
    [Migration("20260928204539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("prefs")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleAccount.Preferences.Data.CatalogModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.ToTable("model_catalog", "prefs");

                    b.HasData(
                        new
                        {
                            Id = "claude-opus-5",
                            DisplayName = "Claude Opus 5",
                            IsActive = true,
                            Vendor = "Anthropic"
                        },
                        new
                        {
                            Id = "claude-sonnet-5",
                            DisplayName = "Claude Sonnet 5",
                            IsActive = true,
                            Vendor = "Anthropic"
                        },
                        new
                        {
                            Id = "claude-haiku-4-5",
                            DisplayName = "Claude Haiku 4.5",
                            IsActive = true,
                            Vendor = "Anthropic"
                        },
                        new
                        {
                            Id = "gpt-5-codex",
                            DisplayName = "GPT-5 Codex",
                            IsActive = true,
                            Vendor = "OpenAI"
                        },
                        new
                        {
                            Id = "gemini-3-pro",
                            DisplayName = "Gemini 3 Pro",
                            IsActive = true,
                            Vendor = "Google"
                        });
                });

            modelBuilder.Entity("SimpleAccount.Preferences.Data.UserModelPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ModelId")
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("UserId", "ModelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ux_user_model_preferences_user_rank");

                    b.ToTable("user_model_preferences", "prefs");
                });

            modelBuilder.Entity("SimpleAccount.Preferences.Data.UserModelPreference", b =>
                {
                    b.HasOne("SimpleAccount.Preferences.Data.CatalogModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });
#pragma warning restore 612, 618
        }
    }
}
